# sync data files from piney-point

load(url("https://tbep-tech.github.io/piney-point/data/bsstatloc.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/bstransect.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/bstransectocc.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/bswqdat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/bswqdatsub.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/bswqrngs.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/lobodat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/loboeco.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/macrodat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/mcrtmp.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/parms.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/ppseg.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rsallpts.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rsbntpts.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rscntdat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rscntthr.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rsphydat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rsphypts.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rsstatloc.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rstrndatmcr.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rstrndatsav.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rstrnlns.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rstrnpts.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rswqdat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/savtmp.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/sbshed.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/segmask.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/tbhished.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/trnlns.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/trnpts.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/wqrefmap.RData"))
save(bsstatloc, file = "data/bsstatloc.RData", version = 2)
save(bstransect, file = "data/bstransect.RData", version = 2)
save(bstransectocc, file = "data/bstransectocc.RData", version = 2)
save(bswqdat, file = "data/bswqdat.RData", version = 2)
save(bswqdatsub, file = "data/bswqdatsub.RData", version = 2)
save(bswqrngs, file = "data/bswqrngs.RData", version = 2)
save(lobodat, file = "data/lobodat.RData", version = 2)
save(loboeco, file = "data/loboeco.RData", version = 2)
save(macrodat, file = "data/macrodat.RData", version = 2)
save(mcrtmp, file = "data/mcrtmp.RData", version = 2)
save(parms, file = "data/parms.RData", version = 2)
save(ppseg, file = "data/ppseg.RData", version = 2)
save(rsallpts, file = "data/rsallpts.RData", version = 2)
save(rsbntpts, file = "data/rsbntpts.RData", version = 2)
save(rscntdat, file = "data/rscntdat.RData", version = 2)
save(rscntthr, file = "data/rscntthr.RData", version = 2)
save(rsphydat, file = "data/rsphydat.RData", version = 2)
save(rsphypts, file = "data/rsphypts.RData", version = 2)
save(rsstatloc, file = "data/rsstatloc.RData", version = 2)
save(rstrndatmcr, file = "data/rstrndatmcr.RData", version = 2)
save(rstrndatsav, file = "data/rstrndatsav.RData", version = 2)
save(rstrnlns, file = "data/rstrnlns.RData", version = 2)
save(rstrnpts, file = "data/rstrnpts.RData", version = 2)
save(rswqdat, file = "data/rswqdat.RData", version = 2)
save(savtmp, file = "data/savtmp.RData", version = 2)
save(sbshed, file = "data/sbshed.RData", version = 2)
save(segmask, file = "data/segmask.RData", version = 2)
save(tbhished, file = "data/tbhished.RData", version = 2)
save(trnlns, file = "data/trnlns.RData", version = 2)
save(trnpts, file = "data/trnpts.RData", version = 2)
save(wqrefmap, file = "data/wqrefmap.RData", version = 2)