# sync data files from piney-point

load(url("https://tbep-tech.github.io/piney-point/data/bsstatloc.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/bstransect.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/bstransectocc.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/bswqdat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/bswqdatsub.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/bswqrngs.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/lobodat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/loboeco.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/macrodat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/mcrtmp.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/parms.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/ppseg.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rsallpts.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rsbntpts.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rscntdat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rscntthr.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rsphydat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rsphypts.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rsstatloc.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rstrndatmcr.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rstrndatsav.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rstrnlns.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rstrnpts.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/rswqdat.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/savtmp.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/sbshed.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/segmask.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/tbhished.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/trnlns.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/trnpts.RData")) 
load(url("https://tbep-tech.github.io/piney-point/data/wqrefmap.RData"))
save(bsstatlocfile = "data/bsstatloc.RData", version = 2)
save(bstransectfile = "data/bstransect.RData", version = 2)
save(bstransectoccfile = "data/bstransectocc.RData", version = 2)
save(bswqdatfile = "data/bswqdat.RData", version = 2)
save(bswqdatsubfile = "data/bswqdatsub.RData", version = 2)
save(bswqrngsfile = "data/bswqrngs.RData", version = 2)
save(lobodatfile = "data/lobodat.RData", version = 2)
save(loboecofile = "data/loboeco.RData", version = 2)
save(macrodatfile = "data/macrodat.RData", version = 2)
save(mcrtmpfile = "data/mcrtmp.RData", version = 2)
save(parmsfile = "data/parms.RData", version = 2)
save(ppsegfile = "data/ppseg.RData", version = 2)
save(rsallptsfile = "data/rsallpts.RData", version = 2)
save(rsbntptsfile = "data/rsbntpts.RData", version = 2)
save(rscntdatfile = "data/rscntdat.RData", version = 2)
save(rscntthrfile = "data/rscntthr.RData", version = 2)
save(rsphydatfile = "data/rsphydat.RData", version = 2)
save(rsphyptsfile = "data/rsphypts.RData", version = 2)
save(rsstatlocfile = "data/rsstatloc.RData", version = 2)
save(rstrndatmcrfile = "data/rstrndatmcr.RData", version = 2)
save(rstrndatsavfile = "data/rstrndatsav.RData", version = 2)
save(rstrnlnsfile = "data/rstrnlns.RData", version = 2)
save(rstrnptsfile = "data/rstrnpts.RData", version = 2)
save(rswqdatfile = "data/rswqdat.RData", version = 2)
save(savtmpfile = "data/savtmp.RData", version = 2)
save(sbshedfile = "data/sbshed.RData", version = 2)
save(segmaskfile = "data/segmask.RData", version = 2)
save(tbhishedfile = "data/tbhished.RData", version = 2)
save(trnlnsfile = "data/trnlns.RData", version = 2)
save(trnptsfile = "data/trnpts.RData", version = 2)
save(wqrefmapfile = "data/wqrefmap.RData", version = 2)